### ISSUE TITLE
spiffs.bin

### ISSUE THREAD

**Issue by ON2ACO** [ddaqua6/LoRa_APRS_Meteo#1]
Building FS image from 'data' directory to .pio\build\ttgo-lora32-v1\spiffs.bin
error: can't read source directory
*** [.pio\build\ttgo-lora32-v1\spiffs.bin] Error 1
======================================================== [FAILED] Took 1.42 seconds ========================================================

any ideas to resolve that?  i am running ON2ACO-WX with the first code and all is working perfect, i just want to try out the new one with the sps30 but i have this problem. with this fault even BPM 280 is not recognized.

thx fot any help Thierry ON2ACO  http://WWW.ON2ACO.COM

**Comment by davieldds** [comment]
Hi Thierry! Thanks for interest in the project. I tried to clone this repo and opened with platform io and I compiled it without any problem so I wasn't able to reproduce the error. Please check you have updated all components and that you platform io has internet access and that you access data on your computer.
I hope this helps. If not, please reach me. Thanks!

**Comment by Santibcg** [comment]
Hello. I'm Santi, EB1BCG. I have difficulty finding an anemometer with a hall effect and I would like to know if I can change the code to install another type of anemometer, for example one that sends the signal in RS485 format.
I love this firmware
Thanks a lot.

Hola. Soy Santi, EB1BCG. Tengo dificultad para encontrar un anemómetro con efecto hall y me gustaría saber si se puede cambiar el código para instalar otro tipo de anemómetro, por ejemplo uno que manda la señal en formato RS485.
Me encanta este firmware.
Muchas gracias.

**Comment by davieldds** [comment]
Hello Santi! Thank you very much for using the firmware. Certainly this is possible. Feel free to fork this repo and do the necessary changes (you'll need to implement a different library and change the procedure for reading the value). Unfortunately, time doesn't allow me to do that.

Hola Santi, muchas gracias por usar el firmware. Por cierto se puede hacer esto, puedes hacer fork de este repo y hacer los cambios necesarios (hay que instalar otra librería y cambiar la función para recibir la señal). Lo siento, pero no tengo tiempo suficiente para mí hacerlo.

73 David

**Comment by Santibcg** [comment]
Hi David. Also thank you very much for allowing me to modify your program.
I have managed to read the RS485 anemometer from your program, from there I take the anemometer reading through the serial port. Now I can't find a way to pass that reading (which I have stored in a variable) to the rest of the program so that it appears on the website and on the weather station's beacon. Would you be so kind as to give me a hint?
Thanks a lot. Greetings from Santi, EB1BCG.

Hola David. Igualmente muchas gracias por permitir que modifique tu programa.
He conseguido leer el anemómetro RS485 desde tu programa, desde ahí saco por el puerto serie la lectura del anemómetro. Ahora no encuentro la forma de pasar esa lectura (que tengo almacenada en una variable) al resto del programa para que aparezca en la página web y en la baliza de la estación meteorológica. Serías tan amable de darme una pista?
Muchas gracias. Un saludo de Santi, EB1BCG.

**Comment by davieldds** [comment]
Hi Santi!
Please try to modify the section if (USE_ANEMOMETER) on line 537 and below which processes calculations of wind. Replace the hall sensor readings and calculations with your sensor readings. windMeterSpins is variable for counting the spins of the anemometer, windActualSpeed is wind speed at the moment (it uses diameter of the anemometer in calculation) and windLongPeriodSpeed calculates long-period wind.
Hope this was helpful. 73!

**Comment by Santibcg** [comment]
Hi David. Thanks for the information. I almost have the program finished. When I finish it I will let you know and tell you the details.
Thank you very much for everything.
Greetings from Santi, EB1BCG.

**Comment by davieldds** [comment]
Perfect! You can also fork the repo and request pull to the main repository.
73 David OK2DDS
